# Матрицы и матричные операции. Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

__Решение__

__а)__  Произведение __АВ__ не определено, т.к. количество стольцов в __А__ не равно количеству строк __В__ . Произведение __ВА__ определено, размерность __4х4__

__б)__  Произведение __АВ__ определено, размерность матриц __2х3__ . Произведение __ВА__  не определено, т.к. количество стольцов в __В__ не равно количеству строк __А__

__в)__  Произведение __АВ__ определено, размерность __8х8__ . Произведение __ВА__ определено, размерность __3х3__

__г)__  Произведения __АВ__ и __ВА__ определено, размерность __4х4__



__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__Решение__

Сумма двух матриц __А+В__ = 
$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1+4 & -2 + -1\\ 
3+0 & 0+5  
\end{pmatrix}= \begin{pmatrix}
5 & -3\\ 
3 & 5  
\end{pmatrix}.$$


Произведение двух матриц __АВ__ = 
$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} * \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1\cdot4 + (-2)\cdot0 & 1\cdot(-1) + (-2)\cdot5\\ 
3\cdot4 + 0\cdot0 & 3\cdot(-1) + 0\cdot5  
\end{pmatrix}= \begin{pmatrix}
4 & -11\\ 
12 & -3  
\end{pmatrix}.$$

Произведение двух матриц __ВA__ = 
$$\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} * \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} = \begin{pmatrix}
4\cdot1 + (-1)\cdot3 & 4\cdot(-2) + (-1)\cdot0\\ 
0\cdot1 + 5\cdot3 & 0\cdot(-2) + 5\cdot0  
\end{pmatrix}= \begin{pmatrix}
1 & -8\\ 
15 & 0  
\end{pmatrix}.$$

In [1]:
import numpy as np

In [3]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}\n')
print(f'Матрица B\n{B}\n')
print(f'Матрица С = A + B\n{A + B}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]


In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}\n')
print(f'Матрица B\n{B}\n')
print(f'Матрица С = AB\n{np.dot(A, B)}')
print(f'Матрица С = ВА\n{np.dot(B, A)}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица С = AB
[[  4 -11]
 [ 12  -3]]
Матрица С = ВА
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

__Решение__

$$3A - 2B + 4C = 3\cdot\begin{pmatrix}1 & 7\\3 & -6\end{pmatrix} - 2\cdot\begin{pmatrix}0 & 5\\2 & -1\end{pmatrix} + 4\cdot\begin{pmatrix}2 & -4\\1 & 1\end{pmatrix} = \begin{pmatrix}3*1 & 3*7\\3*3 & 3*(-6)\end{pmatrix} - \begin{pmatrix}2*0 & 2*5\\2*2 & 2*(-1)\end{pmatrix} + \begin{pmatrix}4*2 & 4*(-4)\\4*1 & 4*1\end{pmatrix} = \begin{pmatrix}3-0+8 & 21-10-16\\9-4+4 & -18+2+4\end{pmatrix} = \begin{pmatrix}11 & -5\\9 & -12\end{pmatrix}$$

In [5]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'Матрица A\n{A}\n')
print(f'Матрица B\n{B}\n')
print(f'Матрица C\n{C}\n')
print(f'Матрица D = 3A - 2B + 4C\n{3*A - 2*B + 4*C}')

Матрица A
[[ 1  7]
 [ 3 -6]]

Матрица B
[[ 0  5]
 [ 2 -1]]

Матрица C
[[ 2 -4]
 [ 1  1]]

Матрица D = 3A - 2B + 4C
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}4 & 1\\5 & -2\\2 & 3\end{pmatrix}$. Вычислить $AA^T$ и $A^TA$.

__Решение__

Транспонированная матрица $A^T=\begin{pmatrix}4 & 5 & 2\\1 & -2 & 3\end{pmatrix}$

Произведение $A*A^T = \begin{pmatrix}4 & 1\\5 & -2\\2 & 3\end{pmatrix} * \begin{pmatrix}4 & 5 & 2\\1 & -2 & 3\end{pmatrix} = \begin{pmatrix}17 & 18 & 11\\18 & 29 & 4\\11 & 4 & 13\end{pmatrix}$

Произведение $A^T*A = \begin{pmatrix}4 & 5 & 2\\1 & -2 & 3\end{pmatrix} * \begin{pmatrix}4 & 1\\5 & -2\\2 & 3\end{pmatrix} = \begin{pmatrix}45 & 0\\0 & 14\end{pmatrix}$

In [8]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица A:\n{A}')
print(f'Транспонированная матрица:\n{A.T}')
print(f'Умножение А*Т:\n{np.dot(A, A.T)}')
print(f'Умножение Т*А:\n{np.dot(A.T, A)}')

Матрица A:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
Умножение А*Т:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Умножение Т*А:
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [82]:
def printMatrix ( matrix ): 
   for i in range ( len(matrix) ): 
      for j in range ( len(matrix[i]) ): 
          print ( "{:4d}".format(matrix[i][j]), end = "" ) 
      print ()

while True:
    a1, a2 = input('Введите размерность матрици А (MxN)(через пробел): ').split()
    b1, b2 = input('Введите размерность матрицы В (NxK)(через пробел): ').split()
    a1 = int(a1)
    a2 = int(a2)
    b1 = int(b1)
    b2 = int(b2)
    if a2 == b1:
        break
    else:
        print('Размерность матриц не соответствует условиям MxN и NxK')


a = [[0 for j in range(a1)] for i in range(a2)]
b = [[0 for j in range(b1)] for i in range(b2)]
c = [[0 for j in range(b1)] for i in range(a2)]

for i in range(a2):
    print(f'Введите через пробел значениея {i} строки матрицы А:')
    a_list = input().split()
    j = 0
    for my in a_list:
        a[i][j] = int(my)
        j += 1

for i in range(b2):
    print(f'Введите через пробел значениея {i} строки матрицы В:')
    a_list = input().split()
    j = 0
    for my in a_list:
        b[i][j] = int(my)
        j += 1

print('Матрица А =')
printMatrix(a)
print('Матрица В =')
printMatrix(b)

for i in range(len(a)):
    for j in range(len(b[0])):
        k = 0
        for p in range(len(a[0])):
            k += a[i][p]*b[p][j]
        c[i][j] = k
print('Матрица С = А*В =')
printMatrix(c)


Введите размерность матрици А (MxN)(через пробел): 2 3
Введите размерность матрицы В (NxK)(через пробел): 3 2
Введите через пробел значениея 0 строки матрицы А:
4 1
Введите через пробел значениея 1 строки матрицы А:
5 -2
Введите через пробел значениея 2 строки матрицы А:
2 3
Введите через пробел значениея 0 строки матрицы В:
4 5 2
Введите через пробел значениея 1 строки матрицы В:
1 -2 3
Матрица А =
   4   1
   5  -2
   2   3
Матрица В =
   4   5   2
   1  -2   3
Матрица С = А*В =
  17  18  11
  18  29   4
  11   4  13


# Матрицы и матричные операции. Часть 2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


__Решение__

__а)__ $$\begin{vmatrix}sinx & -cosx\\cosx & sinx\end{vmatrix} = а_{11}*а_{22} - а_{12}*а_{21} = sinx*sinx - cosx*(-cosx) = sin^2x + cos^2x = 1;$$

__б)__  $$\begin{vmatrix}4 & 2 & 3\\0 & 5 & 1\\0 & 0 & 9\end{vmatrix} = 4*\begin{vmatrix}5 & 1\\0 & 9\end{vmatrix} - 2*\begin{vmatrix}0 & 1\\0 & 9\end{vmatrix} + 3*\begin{vmatrix}0 & 5\\0 & 0\end{vmatrix} = 4*(5*9-0*1) - 2*(0*9-0*1) + 3*(0*0-0*5) = 180;$$

__в)__  $$\begin{vmatrix}1 & 2 & 3\\4 & 5 & 6\\7 & 8 & 9\end{vmatrix} = 1*\begin{vmatrix}5 & 6\\8 & 9\end{vmatrix} - 2*\begin{vmatrix}4 & 6\\7 & 9\end{vmatrix} + 3*\begin{vmatrix}4 & 5\\7 & 8\end{vmatrix} = 1*(5*9-8*6) - 2*(4*9-7*6) + 3*(4*8-7*5) = -3 +12 -9 = 0.$$

In [16]:
x = np.pi
b = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])
print(f'Матрица:\n{b}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')

Матрица:
[[ 1.2246468e-16  1.0000000e+00]
 [-1.0000000e+00  1.2246468e-16]]
Определитель:
1


In [12]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


In [13]:
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{B}')
print(f'Определитель:\n{np.linalg.det(B):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

__Решение__

   а) $det(A^{2}) = det(A)*det(A) = 4*4 = 16$;
    
   б) $det(A^{T}) = det(A) = 4$;
    
   в) $det(2A) = 2*det(A) = 2*4 = 8$.

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.


__Решение__

$$\begin{pmatrix}-2 & 7 & -3\\4 & -14 & 6\\-3 & 7 & 13\end{pmatrix} = -2*\begin{vmatrix}-14 & 6\\7 & 13\end{vmatrix} - 7*\begin{vmatrix}4 & 6\\-3 & 13\end{vmatrix} + (-3)*\begin{vmatrix}4 & -14\\-3 & 7\end{vmatrix} = -2*(-14*13-7*6) - 7*(4*13-(-3)*6) + (-3)*(4*7-(-3)*(-14)) = 448 - 490 + 42 = 0.$$

In [17]:
B = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{B}')
print(f'Определитель:\n{np.linalg.det(B):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Решение__

   а) $\begin{pmatrix}1 & 2 & 3\\1 & 1 & 1\\2 & 3 & 4\end{pmatrix}$ 3 строка является суммой 1 и 2, значит ее можно отбросить $\begin{pmatrix}1 & 2 & 3\\1 & 1 & 1\end{pmatrix}$ следовательно ранг матрици = 2

   б) $\begin{pmatrix}0 & 0 & 2 & 1\\0 & 0 & 2 & 2\\0 & 0 & 4 & 3\\2 & 3 & 5 & 6\end{pmatrix}$ 3 строка является суммой 1 2 строк, значит ее можно отбросить $\begin{pmatrix}0 & 0 & 2 & 1\\0 & 0 & 2 & 2\\2 & 3 & 5 & 6\end{pmatrix}$ ранг матрицы = 3

In [18]:
B = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Матрица:\n{B}')
print(f'Ранг матрицы: {np.linalg.matrix_rank(B)}')

Матрица:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы: 2


In [19]:
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Матрица:\n{B}')
print(f'Ранг матрицы: {np.linalg.matrix_rank(B)}')

Матрица:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы: 3
