# Системы линейных уравнений. Часть 1

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__Решение__

преобразуем расширенную матрицу системы путем элементарных преобразований:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

от 2 строки отнимаем 1 строку, умноженную на 2; от 3 строки отнимаем 1 строку
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$


2-ую строку умножим на -1
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & 1 & -1 & -5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
2\\
4
\end{matrix}
\end{pmatrix}$$

от 1 строки отнимаем 2 строку
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & 0 & 3\\ 
0 & 1 & -1 & -5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
-2\\ 
2\\
4
\end{matrix}
\end{pmatrix}$$

3-ую строку делим на -2
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & 0 & 3\\ 
0 & 1 & -1 & -5\\ 
0 & 0 & 1 & -1.5
\end{matrix}\right|
\begin{matrix}
-2\\ 
2\\
-2
\end{matrix}
\end{pmatrix}$$

2 строку складываем с 3 строкой
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & 0 & 3\\ 
0 & 1 & 0 & -6.5\\ 
0 & 0 & 1 & -1.5
\end{matrix}\right|
\begin{matrix}
-2\\ 
0\\
-2
\end{matrix}
\end{pmatrix}$$

__Система имеет множество решений:__

$\begin{cases}
x_{1}+3x_{4}=-2, \\
x_{2}-6.5x_{4}=0, \\
x_{3}-1.5x_{4}=-2;
\end{cases}$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

__Решение__

__а)__ преобразуем расширенную матрицу системы путем элементарных преобразований:

$$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1\\ 
2 & -5 & -3\\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$$

делим 1 строку на 3
$$\begin{pmatrix}
\left.\begin{matrix}
1 & -\frac{1}{3} & \frac{1}{3}\\ 
2 & -5 & -3\\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
\frac{4}{3}\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$$

от 2 строки отнимаем 1 строку, умноженную на 2; от 3 строки отнимаем 1 строку
$$\begin{pmatrix}
\left.\begin{matrix}
1 & -\frac{1}{3} & \frac{1}{3}\\ 
0 & -\frac{13}{3} & -\frac{11}{3}\\ 
0 & \frac{4}{3} & -\frac{4}{3}
\end{matrix}\right|
\begin{matrix}
\frac{4}{3}\\ 
-\frac{59}{3}\\
-\frac{4}{3}
\end{matrix}
\end{pmatrix}$$

2-ую строку делим на $-\frac{13}{3}$
$$\begin{pmatrix}
\left.\begin{matrix}
1 & -\frac{1}{3} & \frac{1}{3}\\ 
0 & 1 & \frac{11}{13}\\ 
0 & \frac{4}{3} & -\frac{4}{3}
\end{matrix}\right|
\begin{matrix}
\frac{4}{3}\\ 
\frac{59}{13}\\
-\frac{4}{3}
\end{matrix}
\end{pmatrix}$$


к 1 строке добавляем 2 строку, умноженную на   $\frac{1}{3}$ ; от 3 строки отнимаем 2 строку, умноженную на $\frac{4}{3}$
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & \frac{8}{13}\\ 
0 & 1 & \frac{11}{13}\\ 
0 & 0 & -\frac{32}{13}
\end{matrix}\right|
\begin{matrix}
\frac{37}{13}\\ 
\frac{59}{13}\\
-\frac{96}{13}
\end{matrix}
\end{pmatrix}$$

3-ую строку делим на $-\frac{32}{13}$
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & \frac{8}{13}\\ 
0 & 1 & \frac{11}{13}\\ 
0 & 0 & 1
\end{matrix}\right|
\begin{matrix}
\frac{37}{13}\\ 
\frac{59}{13}\\
3
\end{matrix}
\end{pmatrix}$$

от 1 строки отнимаем 3 строку, умноженную на $\frac{8}{13}$ ; от 2 строки отнимаем 3 строку, умноженную на $\frac{11}{13}$
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & 0\\ 
0 & 1 & 0\\ 
0 & 0 & 1
\end{matrix}\right|
\begin{matrix}
1\\ 
2\\
3
\end{matrix}
\end{pmatrix}$$

Получаем:
$\begin{cases}
x_{1}=1, \\
x_{2}=2, \\
x_{3}=3;
\end{cases}$

Проверяем:
$\begin{cases}
3·1 - 2 + 3 = 3 - 2 + 3 = 4, \\
2·1 - 5·2 - 3·3 = 2 - 10 - 9 = -17, \\
1 + 2 - 3 = 1 + 2 - 3 = 0;
\end{cases}$

Проверка выполнена успешно, система имеет единственное решение, значит совместна.

__б)__ преобразуем расширенную матрицу системы путем элементарных преобразований:

$$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\ 
1 & -2 & 3\\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}$$

1-ую строку делим на 2
$$\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3\\ 
1 & -2 & 3\\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
0.5\\ 
-2\\
5
\end{matrix}
\end{pmatrix}$$

от 2 строки отнимаем 1 строку; от 3 строки отнимаем 1 строку, умноженную на 3
$$\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3\\ 
0 & 0 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
0.5\\ 
-2.5\\
3.5
\end{matrix}
\end{pmatrix}$$

Система уравнений не имеет решения, т.к. вторая и третья строки 0 = -2.5; 0 = 3.5 не имеют смысла.

__в)__ преобразуем расширенную матрицу системы путем элементарных преобразований:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\ 
3 & 1 & -8 
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}$$

от 2 строки отнимаем 1 строку, умноженную на 3
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\ 
0 & -5 & -23 
\end{matrix}\right|
\begin{matrix}
4\\ 
-14
\end{matrix}
\end{pmatrix}$$

2 строку делим на -5
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\ 
0 & 1 & 4.6 
\end{matrix}\right|
\begin{matrix}
4\\ 
2.8
\end{matrix}
\end{pmatrix}$$

от 1 строки отнимаем 2 строку, умноженную на 2
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & -4.2\\ 
0 & 1 & 4.6 
\end{matrix}\right|
\begin{matrix}
-1.6\\ 
2.8
\end{matrix}
\end{pmatrix}$$

Получаем:
$\begin{cases}
x_{1} - 4.2x_{3} = -1.6, \\
x_{2} + 4.6x{3} = 2.8
\end{cases}$

Система имеет множество решений.

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

__Решение__

Произведем преобразование матрицы:
2 строку делим на 5
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 1 & 0 & 0.2\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
0.4\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

от 1 строки отнимаем 2 строку, умноженную на 3
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & -2 & 3.4\\ 
0 & 1 & 0 & 0.2\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
1.8\\ 
0.4\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

3 строку делим на 3
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & -2 & 3.4\\ 
0 & 1 & 0 & 0.2\\ 
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
1.8\\ 
0.4\\
\frac{4}{3}\\
1
\end{matrix}
\end{pmatrix}.$$

к 1 строке добавляем 3 строку, умноженную на 2
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & 0 & 3.4\\ 
0 & 1 & 0 & 0.2\\ 
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
\frac{67}{15}\\ 
0.4\\
\frac{4}{3}\\
1
\end{matrix}
\end{pmatrix}.$$

4 строку делим на 2
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & 0 & 3.4\\ 
0 & 1 & 0 & 0.2\\ 
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & 1
\end{matrix}\right|
\begin{matrix}
\frac{67}{15}\\ 
0.4\\
\frac{4}{3}\\
0.5
\end{matrix}
\end{pmatrix}.$$

от 1 строки отнимаем 4 строку, умноженную на 3.4; от 2 строки отнимаем 4 строку, умноженную на 0.2
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & 0 & 0\\ 
0 & 1 & 0 & 0\\ 
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & 1
\end{matrix}\right|
\begin{matrix}
\frac{83}{30}\\ 
0.3\\
\frac{4}{3}\\
0.5
\end{matrix}
\end{pmatrix}.$$

Получаем:
$\begin{cases}
x_{1}=\frac{83}{30}, \\
x_{2}=0.3, \\
x_{3}=\frac{4}{3}, \\
x_{4}=0.5;
\end{cases}$

Делаем проверку:
$\begin{cases}
\frac{83}{30} + 3·0.3 - 2·\frac{4}{3} + 4·0.5 = \frac{83}{30} + 0.9 - \frac{8}{3} + 2 = 3, \\
5·0.3 + 0.5 = 1.5 + 0.5 = 2, \\
3·\frac{4}{3} = 4 = 4, \\
2·0.5 = 1 = 1
\end{cases}$

Проверка выполнена успешно, система имеет единственное решение и является совместной.

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

__Решение__

Для определения значей $a, b$ и $c$ найдем ранги матрицы $A$ и $\tilde{A}$<br>
Причем:<br>
1) если $rankA=rank \tilde A=n$, где $n$ — число неизвестных, то система определена, т. е. имеет единственное решение;<br>
2) если $rankA=rank \tilde A<n$, то система имеет бесконечное количество решений;<br>
3) если $rankA<rank \tilde A$, то система несовместна.

для начала примем значения $a = 0$, $b = 0$, $c = 0$

In [11]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 2, 3, 0], [4, 5, 6, 0], [7, 8, 9, 0]])

print(f'Матрица a\n{a}')
print(f'Ранг матрицы a: {np.linalg.matrix_rank(a)}')
print(f'Матрица b\n{b}')
print(f'Ранг матрицы b: {np.linalg.matrix_rank(b)}')

Матрица a
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Ранг матрицы a: 2
Матрица b
[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]
Ранг матрицы b: 2


При таких значениях $a$, $b$ и $c$ $rankA=rank \tilde A<n$ система имеет бесконечное количество решений;<br>

Присвоим значение $a = 1$, $b = 0$, $c = 0$

In [16]:
b1 = np.array([[1, 2, 3, 1], [4, 5, 6, 0], [7, 8, 9, 0]])
print(f'Матрица b1\n{b1}')
print(f'Ранг матрицы b1: {np.linalg.matrix_rank(b1)}')

Матрица b1
[[1 2 3 1]
 [4 5 6 0]
 [7 8 9 0]]
Ранг матрицы b1: 3


При таких значениях $a$, $b$ и $c$ $rankA<rank \tilde A$ система несовместна.

# Системы линейных уравнений. Часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

__Решение__

__а)__ Найдем определитель матрицы коэффициентов:

$$detA=\begin{vmatrix}
1 & -2\\ 
3 & -4 
\end{vmatrix}=
=1 \cdot(-4)-3\cdot (-2)=-4 + 6 = 2\neq 0,$$

следовательно, система совместна.

Найдем определители $detA_{1}$, $detA_{2}$:

$$detA_{1}=\begin{vmatrix}
1 & -2\\ 
7 & -4 
\end{vmatrix}=
=1 \cdot(-4)-7\cdot (-2)=-4 + 14 = 10,$$

$$detA_{2}=\begin{vmatrix}
1 & 1\\ 
3 & 7 
\end{vmatrix}=
=1 \cdot7-3\cdot 1=7 - 3 = 4$$

Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2$$

__в)__ Найдем определитель матрицы коэффициентов:

$$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\
2 & 4 & 1
\end{vmatrix}=
=2 \cdot 1 \cdot 1 + (-1) \cdot (-3) \cdot 2 + 5 \cdot 1 \cdot 4 - 5 \cdot 1 \cdot 2 - 2 \cdot (-3) \cdot 4 - (-1) \cdot 1 \cdot 1 = 2 + 6 + 20 - 10 + 24 + 1 = 43\neq 0,$$

следовательно, система совместна.

Найдем определители $detA_{1}$, $detA_{2}$, $detA_{3}$:

$$detA_{1}=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\
1 & 4 & 1
\end{vmatrix}=
=10 \cdot 1 \cdot 1 + (-1) \cdot (-3) \cdot 1 + 5 \cdot (-2) \cdot 4 - 5 \cdot 1 \cdot 1 - 10 \cdot (-3) \cdot 4 - (-1) \cdot (-2) \cdot 1 = 10 + 3 - 40 - 5 + 120 - 2 = 86,$$

$$detA_{2}=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\
2 & 1 & 1
\end{vmatrix}=
=2 \cdot (-2) \cdot 1 + 10 \cdot (-3) \cdot 2 + 5 \cdot 1 \cdot 1 - 5 \cdot (-2) \cdot 2 - 2 \cdot (-3) \cdot 1 - 10 \cdot 1 \cdot 1 = -4 - 60 + 5 + 20 + 6 - 10 = -43,$$

$$detA_{3}=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\
2 & 4 & 1
\end{vmatrix}=
=2 \cdot 1 \cdot 1 + (-1) \cdot (-2) \cdot 2 + 10 \cdot 1 \cdot 4 - 10 \cdot 1 \cdot 2 - 2 \cdot (-2) \cdot 4 - (-1) \cdot 1 \cdot 1 = 2 + 4 + 40 - 20 + 16 + 1 = 43,$$

Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2,$$

$$x_{2} = \frac{detA_{2}}{detA} = -\frac{43}{43}=-1$$

$$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1$$

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

__Решение__

__а)__ Представим $A$ в виде: $A = LU$

Вычисляем значение элемента $L_{11} = 1$

$U_{11} = \frac{1}{1} = 1$

$U_{12} = \frac{2}{1} = 2$

$U_{13} = \frac{4}{1} = 4$

Вычисляем значение элемента $L_{21} = 2$

Вычисляем значение элемента $L_{22} = 9 - (2 \cdot 2) = 5$

$U_{22} = \frac{5}{5} = 1$

$U_{23} = \frac{4}{5} = 0.8$

Вычисляем значение элемента $L_{31} = 3$

Вычисляем значение элемента $L_{32} = 26 - (3 \cdot 2) = 20$

Вычисляем значение элемента $L_{33}= 30 - (3 \cdot 4 + 20 \cdot 0.8) = 2$

$U_{33} = \frac{2}{2} = 1$

Получили матрицы $L$ и $U$: $$L = \begin{pmatrix}1 & 0 & 0\\2 & 5 & 0\\3 & 20 & 2\end{pmatrix}$$
$$U = \begin{pmatrix}1 & 2 & 4\\0 & 1 & 0.8\\0 & 0 & 1\end{pmatrix}$$

Проверим: $A = LU$ $$A = \begin{pmatrix}1 & 0 & 0\\2 & 5 & 0\\3 & 20 & 2\end{pmatrix} \cdot \begin{pmatrix}1 & 2 & 4\\0 & 1 & 0.8\\0 & 0 & 1\end{pmatrix} = \begin{pmatrix}1 & 2 & 4 \\ 2 & 9 & 12 \\ 3 & 26 & 30\end{pmatrix}$$

__б)__ Представим $A$ в виде: $A = LU$

Вычисляем значение элемента $L_{11} = 1$

$U_{11} = \frac{1}{1} = 1$

$U_{12} = \frac{1}{1} = 1$

$U_{13} = \frac{2}{1} = 2$

$U_{14} = \frac{4}{1} = 4$

Вычисляем значение элемента $L_{21} = 2$

Вычисляем значение элемента $L_{22} = 5 - (2 \cdot 1) = 3$

$U_{22} = \frac{3}{3} = 1$

$U_{23} = \frac{4}{3}$

$U_{24} = \frac{1}{3}$

Вычисляем значение элемента $L_{31} = 3$

Вычисляем значение элемента $L_{32} = 18 - (3 \cdot 1) = 15$

Вычисляем значение элемента $L_{33} = 29 - (3 \cdot 2 + 15 \cdot 1.33) = 3$

$U_{33} = \frac{3}{3} = 1$

$U_{34} = \frac{1}{3}$

Вычисляем значение элемента $L_{41} = 4$

Вычисляем значение элемента $L_{42} = 22 - (4 \cdot 1) = 18$

Вычисляем значение элемента $L_{43} = 53 - (4 \cdot 2 + 18 \cdot 1.33) = 21$

Вычисляем значение элемента $L_{44} = 33 - (4 \cdot 4 + 18 \cdot 0.33 + 21 \cdot 0.33) = 4$

$U_{44} = \frac{4}{4} = 1$

Получили матрицы $L$ и $U$: $$L = \begin{pmatrix}1 & 0 & 0 & 0\\2 & 3 & 0 & 0\\3 & 15 & 3 & 0\\4 & 18 & 21 & 4\end{pmatrix}$$
$$U = \begin{pmatrix}1 & 1 & 2 & 4\\0 & 1 & \frac{4}{3} & \frac{1}{3}\\0 & 0 & 1 & \frac{1}{3}\\0 & 0 & 0 & 1\end{pmatrix}$$

Проверим: $A = LU$ $$A = \begin{pmatrix}1 & 0 & 0 & 0\\2 & 3 & 0 & 0\\3 & 15 & 3 & 0\\4 & 18 & 21 & 4\end{pmatrix} \cdot \begin{pmatrix}1 & 1 & 2 & 4\\0 & 1 & \frac{4}{3} & \frac{1}{3}\\0 & 0 & 1 & \frac{1}{3}\\0 & 0 & 0 & 1\end{pmatrix} = \begin{pmatrix}1 & 1 & 2 & 4\\2 & 5 & 8 & 9\\3 & 18 & 29 & 18\\4 & 22 & 53 & 33\end{pmatrix}$$

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__Решение__

Представим систему уравнений в виде матрицы:
$$A=\begin{pmatrix}
\left.\begin{matrix}
2 & 1 & 3\\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{matrix}\right|
\begin{matrix}
1\\ 
-6\\
-5
\end{matrix}
\end{pmatrix}.$$

Представим $A$ в виде: $A = LU$

Вычисляем значение элемента $L_{11} = 2$

$U_{11} = \frac{2}{2} = 1$

$U_{12} = \frac{1}{2} = 0.5$

$U_{13} = \frac{3}{2} = 1.5$

Вычисляем значение элемента $L_{21} = 11$

Вычисляем значение элемента $L_{22} = 7 - (11 \cdot 0.5) = 1.5$

$U_{22} = \frac{1.5}{1.5} = 1$

$U_{23} = \frac{-11.5}{1.5} = -7.667$

Вычисляем значение элемента $L_{31} = 9$

Вычисляем значение элемента $L_{32} = 8 - (9 \cdot 0.5) = 3.5$

Вычисляем значение элемента $L_{33} = 4 - (9 \cdot 1.5 + 3.5 \cdot -7.67) = 17.33$

$U_{33} = \frac{17.333}{17.333} = 1$

Получили матрицы $L$ и $U$: $$L = \begin{pmatrix}2 & 0 & 0\\11 & 1.5 & 0\\9 & 3.5 & 17.333\end{pmatrix}$$
$$U = \begin{pmatrix}1 & 0.5 & 1.5\\0 & 1 & -7.667\\0 & 0 & 1\end{pmatrix}$$

Вычисляем значения $y_i$

$y_1 = \frac{1}{2} = 0.5$

$y_2 = \frac{-6 - 11 \cdot 0.5}{1.5} = -7.67$

$y_3 = \frac{-5 - 9 \cdot 0.5 + 3.5 \cdot (-7.67)}{17.33} = 1$

Вычисляем значения $x_i$

$x_3 = y_3 = 1$

$x_2 = -7.67 - (-7.67 \cdot 1 ) = 0$

$x_1 = 0.5 - (0.5 \cdot 0 + 1.5 \cdot 1 ) = -1$

Подставим полученные значения $x_i$ в уравнение:
$$\begin{cases}
2 \cdot (-1) + 0 + 3 \cdot 1 = 1 \\
11 \cdot (-1) + 7 \cdot 0 + 5 \cdot 1 = -6 \\
9 \cdot (-1) + 8 \cdot 0 + 4 \cdot 1 = -5
\end{cases}$$

Уравнение решено.

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

__Решение__

Представим сестему уравнений в виде матриц:
$$А = \begin{pmatrix}81 & -45 & 45 \\-45 & 50 & -15 \\45 & -15 & 38\end{pmatrix}; b = \begin{pmatrix}531\\-460\\193\end{pmatrix}$$

Находим элементы матрицы L:

$l_{11} = \sqrt{81} = 9;$  $l_{21} = \frac{-45}{9} = -5;$  $l_{31} = \frac{45}{9} = 5$

$l_{22} = \sqrt{50 - (-5)^2} = 5;$   $l_{32} = \frac{-15 - 5(-5)}{5} = 2$

$l_{33} = \sqrt{38 - 5^2 - 2^2} = 3$

Получили разложение матрицы $A = LL^T$
$$А = LL^T = \begin{pmatrix}9 & 0 & 0 \\-5 & 5 & 0 \\5 & 2 & 3\end{pmatrix} \cdot \begin{pmatrix}9 & -5 & 5 \\0 & 5 & 2 \\0 & 0 & 3\end{pmatrix}$$

Решаем полученные системы $L_y = b$

$$\begin{cases}
9 \cdot y_1 + 0 \cdot y_2 + 0 \cdot y_3 = 531 \\
-5 \cdot y_1 + 5 \cdot y_2 + 0 \cdot y_3 = -460 \\
5 \cdot y_1 + 2 \cdot y_2 + 3 \cdot y_3 = 193
\end{cases}$$

Получаем: $y_1 = 59$;  $y_2 = -33$;  $y_3 = -12$

Теперь решаем систему уравнений ${L^T}_x = y$

$$\begin{cases}
9 \cdot x_1 + -5 \cdot x_2 + 5 \cdot x_3 = 59 \\
0 \cdot x_1 + 5 \cdot x_2 + 2 \cdot x_3 = -33 \\
0 \cdot x_1 + 0 \cdot x_2 + 3 \cdot x_3 = -12
\end{cases}$$

Получаем: $x_1 = 6$; $x_2 = -5$;  $x_3 = -4$

Для проверки подставим значения в уравнения:

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}
\rightarrow
\begin{cases}
81 \cdot 6 - 45 \cdot (-5) + 45 \cdot (-4) = 531 \\
-45 \cdot 6 + 50 \cdot (-5) - 15 \cdot (-4) = -460 \\
45 \cdot 6 - 15 \cdot (-5) + 38 \cdot (-4) = 193
\end{cases}$$

Уравнение решено.

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.