In [1]:
import numpy as np

np.set_printoptions(precision=2, suppress=True)

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

__Решение__

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix} = 
\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix}=0,$$

$(-1-\lambda)(6-\lambda)-2(-6)=0$; 

$\lambda^2-5\lambda+6=0$; 

$D=1$;  $\lambda_1=2$;  $\lambda_2=3$

Получили собственные значения: $\lambda_1=2$;  $\lambda_2=3$

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_1\\ 
x_2 
\end{pmatrix}=
2
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}.
$$
$$\begin{cases}
-x_1-6x_2=2x_1\\ 
2x_1+6x_2=2x_2
\end{cases}
\Rightarrow
\begin{cases}
-x_1-2x_2=0\\ 
x_1+2x_2=0
\end{cases}
\Rightarrow
x_1=-2x_2$$

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_1\\ 
x_2 
\end{pmatrix}=
3
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}.
$$
$$\begin{cases}
-x_1-6x_2=3x_1\\ 
2x_1+6x_2=3x_2
\end{cases}
\Rightarrow
\begin{cases}
-2x_1-3x_2=0\\ 
2x_1+3x_2=0
\end{cases}
\Rightarrow
x_2=-\frac{2}{3}x_1$$

Получили матрицу собственных векторов:
$$\begin{pmatrix}
-2x_2 & x_1\\ 
x_2 & -\frac{2}{3}x_1
\end{pmatrix}$$

In [2]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

__Решение__

Для решения возьмем вектор $x=(1, 1)$
Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором 

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

Из этого будет следовать, что 

$$\begin{cases}
-1+0=1\cdot\lambda \\ 
0+(-1) = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=-1\\ 
\lambda=-1
\end{cases}
\Rightarrow
\lambda=-1.$$

Таким образом, вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение составляет $\lambda=-1.$

In [3]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.


__Решение__

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором 

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

Из этого будет следовать, что 

$$\begin{cases}
1+1=1\cdot\lambda \\ 
-1+3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}
\Rightarrow
\lambda=2.$$

Таким образом, вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение составляет $\lambda=2.$

In [5]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


**4.** Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

__Решение__

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора. Аналогично методике из предыдущего примера получим:

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$$

$$\Rightarrow
\begin{cases}
3\lambda=-9\\ 
-3\lambda=9\\
-4\lambda=-12
\end{cases}
\Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
\lambda=3
\end{cases}
$$

Такая система не имеет смысла, следовательно, вектор $x=(3,-3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A$.

In [4]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]
